apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  namespace: message-queue
data:
  # ── Database ────────────────────────────────────────────────────
  DB_HOST: 'host.docker.internal'
  DB_PORT: '5432'
  DB_NAME: 'product_db'

  # ── App ─────────────────────────────────────────────────────────
  # No SQS — product-service does not publish or consume messages
  PORT: '3003'
  NODE_ENV: 'production'
